version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: morpho_blue_reallocation_bot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ponder
      POSTGRES_PASSWORD: ponder
      POSTGRES_DB: ponder
    ports:
      - "5432:5432"
    volumes:
      - morpho_blue_reallocation_bot_postgres:/var/lib/postgres/data

volumes:
  morpho_blue_reallocation_bot_postgres:
